### ISSUE TITLE
Sagemaker PyTorch Not Recognizing Model_FN

### ISSUE THREAD

**Issue by zacharyFerretti** [aws/sagemaker-pytorch-container#157]
If this is not the right place to ask this I apologize, but I wasn't sure where else to post!

Preamble
===
I have developed a custom PyTorch Neural Network model for predicting whether or not two colors are complimentary. In order to make it more publicly accessible I have begun looking into hosting it on AWS. 

At first I hoped that I would be able to host something simple by loading the torch model's `.PT` file in E3 and making endpoints in AWS lambda which load that model and make a prediction, but I quickly found out this would not be feasible. So then I looked into AWS Sagemaker. After a bit of toying I *was* able to load my torch model and make predictions in Sagemaker notebooks, however I could not deploy the notebook to allow endpoints to access it no matter what I tried.  

Eventually I found this [useful tutorial on developing your own custom ML model](https://towardsdatascience.com/brewing-up-custom-ml-models-on-aws-sagemaker-e09b64627722) for docker based off of Sagemaker. I have primarily followed along with the tutorial, but changing it to serve my own purposes (i.e. using the Pytorch docker base container, using my own model configuration etc. etc.). 

The Problem
==
My model trains properly and I can run the docker image to serve the model up. When I ping the docker image I get a healthy response back and this is the response I get server-side:

```2020-01-30 02:58:09,711 [INFO ] pool-1-thread-7 ACCESS_LOG - /IP:STUFF "GET /ping HTTP/1.1" 200 ```

Yet when I try and make a prediction, using this command 

``` 
command:
      
    ./predict.sh localhost:8080 example.csv text/csv

./predict.sh:
      
    #!/bin/bash

    url=$1
    payload=$2
    content=${3:-text/csv}

    curl --data-binary @${payload} -H "Content-Type: ${content}" -v ${url}/invocations
```

The curl call hangs, and server side I keep running into this error report:

```
2020-01-30 03:06:41,652 [INFO ] W-9001-model com.amazonaws.ml.mms.wlm.WorkerThread - Backend response time: 2
2020-01-30 03:06:41,652 [WARN ] W-9001-model com.amazonaws.ml.mms.wlm.WorkerThread - Backend worker thread exception.
java.lang.IllegalArgumentException: reasonPhrase contains one of the following prohibited characters: \r\n:
Please provide a model_fn implementation.
See documentation for model_fn at https://github.com/aws/sagemaker-python-sdk

	at io.netty.handler.codec.http.HttpResponseStatus.<init>(HttpResponseStatus.java:555)
	at io.netty.handler.codec.http.HttpResponseStatus.<init>(HttpResponseStatus.java:537)
	at io.netty.handler.codec.http.HttpResponseStatus.valueOf(HttpResponseStatus.java:465)
	at com.amazonaws.ml.mms.wlm.Job.response(Job.java:85)
	at com.amazonaws.ml.mms.wlm.BatchAggregator.sendResponse(BatchAggregator.java:85)
	at com.amazonaws.ml.mms.wlm.WorkerThread.run(WorkerThread.java:146)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-01-30 03:06:41,654 [ERROR] W-9001-model com.amazonaws.ml.mms.wlm.BatchAggregator - Unexpected job: PRIVATE_JOB_ID
2020-01-30 03:06:41,656 [INFO ] W-9001-model com.amazonaws.ml.mms.wlm.WorkerThread - Retry worker: 9001 in 1 seconds.
2020-01-30 03:06:41,667 [INFO ] epollEventLoopGroup-4-5 com.amazonaws.ml.mms.wlm.WorkerThread - 9001 Worker disconnected. WORKER_STOPPED
2020-01-30 03:06:42,761 [INFO ] W-9001-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Listening on port: /home/model-server/tmp/.mms.sock.9001
2020-01-30 03:06:42,762 [INFO ] W-9001-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - [PID]126
2020-01-30 03:06:42,762 [INFO ] W-9001-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - MXNet worker started.
2020-01-30 03:06:42,762 [INFO ] W-9001-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Python runtime: 3.6.6
2020-01-30 03:06:42,762 [INFO ] W-9001-model com.amazonaws.ml.mms.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.mms.sock.9001
2020-01-30 03:06:42,766 [INFO ] W-9001-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Connection accepted: /home/model-server/tmp/.mms.sock.9001.
2020-01-30 03:06:43,060 [INFO ] W-9001-model com.amazonaws.ml.mms.wlm.WorkerThread - Backend response time: 293
```

What I Have Already Tried
==

I have read up on the documentation that is listed in that error print out and it seems as if the issue would be that I do not have a `model_fn` implementation. I read [a similar issue someone had here](https://github.com/awslabs/amazon-sagemaker-examples/issues/448) and tried to use their solution to solve the problem (that is I implemented `model_fn`, `input_fn`, `output_fn`, and `predict_fn` in my train file) but it still does not work.

I have tried looking into similar issues such as [this pytorch-container issue](https://github.com/aws/sagemaker-pytorch-container/issues/73) but was not able to use it to fix my problem. It is possible I have the `_fn` series of functions somewhere wrong, but based off of what I have read in other documentation I would be lead to believe it is correct (currently existing in my `train` file).

For Reference
==
To see what my `train` file looks like in `opt/program` I have attached the code of the file minus the actual training part. As you can see most of it is default code so I am not sure what is going wrong.

```
def model_fn(model_dir):
    model = NeuralNet.NeuralNet()
    with open(os.path.join(model_dir, 'model.pt'), 'rb') as f:
        # model.load_state_dict(torch.load(f))
        model = torch.load(f)
    return model


def predict_fn(input_data, model):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model.to(device)
    model.eval()
    with torch.no_grad():
        return model(input_data.to(device))


def input_fn(request_body, request_content_type):
    if request_content_type == 'application/python-pickle':
        return torch.load(BytesIO(request_body))
    else:
        if request_content_type == 'text/csv':
            return pd.read_csv(BytesIO(request_body), header=None, sep=",")


def output_fn(prediction, content_type):
    return json.dumps(prediction)


def train():
```

I am more than happy to add any additional information you may need, and I really appreciate you taking the time to read this!

**Comment by ChuyangDeng** [comment]
Hi @zacharyFerretti, thanks for using SageMaker!

Which version of PyTorch container are you using?  Please note that the SageMaker PyTorch has splitted training/serving into different containers, if you are deploying your trained model, the serving container is what you are looking for: https://github.com/aws/sagemaker-pytorch-serving-container

If you are not using SageMaker Python SDK, you will need to manually pull the serving container.

Thanks,
Chuyang

**Comment by zacharyFerretti** [comment]
Thank you for your response @ChuyangDeng ! I am using the `pytorch-inference:1.3.1` container at the moment. After reading through the documentation that you outlined above I think I may have pinpointed some causes for my issue that is causing my prediction script to fail. 

##### Issue One
Currently when I build my image I just use the command `docker build -t zachs_net .`. My Dockerfile starts off by pulling the `dkr.ecr.us-east-1.amazonaws.com/pytorch-inference:1.3.1-cpu-py36-ubuntu16.04` container as the first thing that it does in it's execution. However I think what you are telling me is that I need to first build a base image following the process outlined on the link you sent me and have the base image built off of the [SageMaker base image](https://github.com/aws/sagemaker-pytorch-container/blob/master/docker/1.0.0/base/Dockerfile.cpu) your team provides here. 

Then I need to follow the steps to develop a final image also outlined in the link you provided. *As I am using the inference container not the proper container and image building process do you think that is most likely what is causing the serve function not to recognize the* `_fn` *series of calls*?

##### Issue Two

If I do need to update the Dockerfile and change it to reference the Sagemaker container that I mention above, what is the name of that container to pull from at the beginning. 

> If you are not using SageMaker Python SDK, you will need to manually pull the serving container.

From what you say here I know I would replace `FROM inference_container` with something like `FROM base:image:url` and `FROM final:image:url` respectively, but I am not sure what the URLs are for those containers. Thanks!

##### Issue Three

If they are not one of the other issues I think it could have to do with is where I have stored and am using the `_fn` series of functions. I have those stored in my `train` file should they be somewhere else?

Again thank you for reading this and I look forward to hearing back from you!

**Comment by laurenyu** [comment]
You should be able to use the pre-built PyTorch image without building it yourself, i.e. starting your Dockerfile with `FROM dkr.ecr.us-east-1.amazonaws.com/pytorch-inference:1.3.1-cpu-py36-ubuntu16.04`.

When I look at your logs, hidden above the "no `model_fn` error", I see:

```
java.lang.IllegalArgumentException: reasonPhrase contains one of the following prohibited characters: \r\n:
```

This looks perhaps like a Windows-style line ending? Not sure if it's affecting things here.

As for the location of your `_fn` implementations, putting them in your train file should work, assuming the train file is passed correctly to the model/endpoint. Could you share the code you're using to deploy your model to an endpoint?

**Comment by zacharyFerretti** [comment]
Hi Lauren! 

I also thought that I should be able to start my Dockerfile that way, and currently I do pull from that image as a base for my container. I've been programming in a Unix environment, so I am not sure where the Windows-style line endings would be coming in.

The Dockerfile looks like: 

```
COPY zachs_net /opt/program
WORKDIR /opt/program
RUN chmod 777 ./train
RUN chmod 777 ./serve
RUN chmod 777 ./predictor.py
```

Then when I run the command `docker run --rm -v $(pwd)/ml:/opt/ml zachs_net train` I am able to train the model successfully. Then I can serve the model using the command `docker run --rm -p 8080:8080 -v $(pwd)/ml:/opt/ml zachs_net serve`. Below I have attached both the code I have in ./serve which you can see here as well as the output when I serve the container using the command i just described.

./serve
=
```


cpu_count = multiprocessing.cpu_count()

model_server_timeout = os.environ.get('MODEL_SERVER_TIMEOUT', 60)
model_server_workers = int(os.environ.get('MODEL_SERVER_WORKERS', cpu_count))


def sigterm_handler(nginx_pid, gunicorn_pid):
    try:
        os.kill(nginx_pid, signal.SIGQUIT)
    except OSError:
        pass
    try:
        os.kill(gunicorn_pid, signal.SIGTERM)
    except OSError:
        pass

    sys.exit(0)


def start_server():
    print('Starting the inference server with {} workers.'.format(
        model_server_workers))

    # link the log streams to stdout/err so they will be logged to the container logs
    subprocess.check_call(
        ['ln', '-sf', '/dev/stdout', '/var/log/nginx/access.log'])
    subprocess.check_call(
        ['ln', '-sf', '/dev/stderr', '/var/log/nginx/error.log'])

    nginx = subprocess.Popen(['nginx', '-c', '/opt/program/nginx.conf'])
    gunicorn = subprocess.Popen(['gunicorn',
                                 '--timeout', str(model_server_timeout),
                                 '-k', 'gevent',
                                 '-b', 'unix:/tmp/gunicorn.sock',
                                 '-w', str(model_server_workers),
                                 'wsgi:app'])

    signal.signal(signal.SIGTERM, lambda a,
                  b: sigterm_handler(nginx.pid, gunicorn.pid))

    # If either subprocess exits, so do we.
    pids = set([nginx.pid, gunicorn.pid])
    while True:
        pid, _ = os.wait()
        if pid in pids:
            break

    sigterm_handler(nginx.pid, gunicorn.pid)
    print('Inference server exiting')

# The main routine just invokes the start function.


if __name__ == '__main__':
    start_server()
```

Output Post Deploy
=
```
2020-02-13 01:26:39,392 [INFO ] main com.amazonaws.ml.mms.ModelServer -
MMS Home: /opt/conda/lib/python3.6/site-packages
Current directory: /opt/program
Temp directory: /home/model-server/tmp
Number of GPUs: 0
Number of CPUs: 6
Max heap size: 443 M
Python executable: /opt/conda/bin/python
Config file: /etc/sagemaker-mms.properties
Inference address: http://0.0.0.0:8080
Management address: http://0.0.0.0:8080
Model Store: /opt/program/.sagemaker/mms/models
Initial Models: ALL
Log dir: /opt/program/logs
Metrics dir: /opt/program/logs
Netty threads: 0
Netty client threads: 0
Default workers per model: 6
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
2020-02-13 01:26:39,510 [INFO ] main com.amazonaws.ml.mms.wlm.ModelManager - Model model loaded.
2020-02-13 01:26:39,543 [INFO ] main com.amazonaws.ml.mms.ModelServer - Initialize Inference server with: EpollServerSocketChannel.
2020-02-13 01:26:39,661 [INFO ] W-9003-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Listening on port: /home/model-server/tmp/.mms.sock.9003
2020-02-13 01:26:39,662 [INFO ] W-9003-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - [PID]40
2020-02-13 01:26:39,664 [INFO ] W-9003-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - MXNet worker started.
2020-02-13 01:26:39,665 [INFO ] W-9003-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Python runtime: 3.6.6
2020-02-13 01:26:39,669 [INFO ] W-9001-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Listening on port: /home/model-server/tmp/.mms.sock.9001
2020-02-13 01:26:39,670 [INFO ] W-9001-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - [PID]41
2020-02-13 01:26:39,671 [INFO ] W-9001-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - MXNet worker started.
2020-02-13 01:26:39,671 [INFO ] W-9001-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Python runtime: 3.6.6
2020-02-13 01:26:39,677 [INFO ] W-9001-model com.amazonaws.ml.mms.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.mms.sock.9001
2020-02-13 01:26:39,677 [INFO ] W-9003-model com.amazonaws.ml.mms.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.mms.sock.9003
2020-02-13 01:26:39,681 [INFO ] W-9004-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Listening on port: /home/model-server/tmp/.mms.sock.9004
2020-02-13 01:26:39,682 [INFO ] W-9004-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - [PID]42
2020-02-13 01:26:39,682 [INFO ] W-9004-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - MXNet worker started.
2020-02-13 01:26:39,683 [INFO ] W-9004-model com.amazonaws.ml.mms.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.mms.sock.9004
2020-02-13 01:26:39,683 [INFO ] W-9004-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Python runtime: 3.6.6
2020-02-13 01:26:39,685 [INFO ] W-9002-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Listening on port: /home/model-server/tmp/.mms.sock.9002
2020-02-13 01:26:39,686 [INFO ] W-9002-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - [PID]46
2020-02-13 01:26:39,686 [INFO ] W-9002-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - MXNet worker started.
2020-02-13 01:26:39,686 [INFO ] W-9002-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Python runtime: 3.6.6
2020-02-13 01:26:39,687 [INFO ] W-9002-model com.amazonaws.ml.mms.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.mms.sock.9002
2020-02-13 01:26:39,692 [INFO ] W-9005-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Listening on port: /home/model-server/tmp/.mms.sock.9005
2020-02-13 01:26:39,692 [INFO ] W-9005-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - [PID]45
2020-02-13 01:26:39,692 [INFO ] W-9005-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - MXNet worker started.
2020-02-13 01:26:39,692 [INFO ] W-9005-model com.amazonaws.ml.mms.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.mms.sock.9005
2020-02-13 01:26:39,692 [INFO ] W-9005-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Python runtime: 3.6.6
2020-02-13 01:26:39,705 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Listening on port: /home/model-server/tmp/.mms.sock.9000
2020-02-13 01:26:39,705 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - [PID]44
2020-02-13 01:26:39,705 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - MXNet worker started.
2020-02-13 01:26:39,705 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Python runtime: 3.6.6
2020-02-13 01:26:39,706 [INFO ] W-9000-model com.amazonaws.ml.mms.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.mms.sock.9000
2020-02-13 01:26:39,776 [INFO ] main com.amazonaws.ml.mms.ModelServer - Inference API bind to: http://0.0.0.0:8080
2020-02-13 01:26:39,778 [INFO ] W-9001-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Connection accepted: /home/model-server/tmp/.mms.sock.9001.
2020-02-13 01:26:39,780 [INFO ] W-9002-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Connection accepted: /home/model-server/tmp/.mms.sock.9002.
2020-02-13 01:26:39,779 [INFO ] W-9004-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Connection accepted: /home/model-server/tmp/.mms.sock.9004.
2020-02-13 01:26:39,778 [INFO ] W-9005-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Connection accepted: /home/model-server/tmp/.mms.sock.9005.
2020-02-13 01:26:39,778 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Connection accepted: /home/model-server/tmp/.mms.sock.9000.
2020-02-13 01:26:39,780 [INFO ] W-9003-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Connection accepted: /home/model-server/tmp/.mms.sock.9003.
Model server started.
2020-02-13 01:26:40,110 [INFO ] W-9004-model com.amazonaws.ml.mms.wlm.WorkerThread - Backend response time: 270
2020-02-13 01:26:40,121 [INFO ] W-9002-model com.amazonaws.ml.mms.wlm.WorkerThread - Backend response time: 266
2020-02-13 01:26:40,133 [INFO ] W-9003-model com.amazonaws.ml.mms.wlm.WorkerThread - Backend response time: 287
2020-02-13 01:26:40,142 [INFO ] W-9000-model com.amazonaws.ml.mms.wlm.WorkerThread - Backend response time: 299
2020-02-13 01:26:40,145 [INFO ] W-9001-model com.amazonaws.ml.mms.wlm.WorkerThread - Backend response time: 308
2020-02-13 01:26:40,148 [INFO ] epollEventLoopGroup-3-2 ACCESS_LOG - /172.17.0.1:38880 "HEAD / HTTP/1.1" 405 37
2020-02-13 01:26:40,148 [INFO ] epollEventLoopGroup-3-1 ACCESS_LOG - /172.17.0.1:38882 "HEAD / HTTP/1.1" 405 38
2020-02-13 01:26:40,191 [INFO ] W-9005-model com.amazonaws.ml.mms.wlm.WorkerThread - Backend response time: 355
2020-02-13 01:26:40,214 [INFO ] epollEventLoopGroup-3-3 ACCESS_LOG - /172.17.0.1:38886 "HEAD / HTTP/1.1" 405 0
```

**Comment by laurenyu** [comment]
ah, seeing your Dockerfile made me realize what I missed in your original post - the Docker image code expects your inference script to be in `/opt/ml/model/code` ([source](https://github.com/aws/sagemaker-inference-toolkit/blob/a727167b08913b727d3984db196a8a1fc9fdf348/src/sagemaker_inference/environment.py#L35-L36))

**Comment by zacharyFerretti** [comment]
Hi @laurenyu I have tried moving my train file there and still it did not work. For reference this is what my directory architecture looks like currently: 

```
.
├── Dockerfile
├── ml
│   ├── code
│   ├── input
│   │   ├── config
│   │   │   ├── hyperparameters.json
│   │   │   └── resourceConfig.json
│   │   └── data
│   │       └── training
│   │           └── training.csv
│   ├── model
│   │   └── zachs_model.pt
│   └── output
│       ├── failure
│       └── success
└── zachs_net
    ├── NeuralNet.py
    ├── predictor.py
    ├── serve
    └── train
```

I might be missing something, but from what I have read, the Sagemaker Model begins training by calling the `train` script located in `opt/program`. When I try and have any other file organization (_i.e. trying what you suggested_) after building it, when I run `docker run --rm -v $(pwd)/ml:/opt/ml zachs_net train` I get errors with Sagemaker not able to find my training script. Those errors are: 

```
Reporting training FAILURE
framework error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_containers/_trainer.py", line 56, in train
    env = sagemaker_containers.training_env()
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_containers/__init__.py", line 26, in training_env
    resource_config=_env.read_resource_config(),
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_containers/_env.py", line 237, in read_resource_config
    return _read_json(resource_config_file_dir)
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_containers/_env.py", line 194, in _read_json
    return json.load(f)
  File "/opt/conda/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/opt/conda/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/bin/dockerd-entrypoint.py", line 27, in <module>
    subprocess.check_call(shlex.split(' '.join(sys.argv[1:])))
  File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['train']' returned non-zero exit status 1.
```

**Comment by laurenyu** [comment]
what I meant is that the file with your `model_fn` implementation should be under `/opt/ml/model/code` ([source code](https://github.com/aws/sagemaker-inference-toolkit/blob/master/src/sagemaker_inference/environment.py#L35-L36)) - I thought from your first post that it was in a file called `train` ("To see what my `train` file looks like in `opt/program`...")

then you should be able to run `docker [...] serve` for serving the model - I assume based on the previous correspondence here that you were already able to train your model successfully

**Comment by zacharyFerretti** [comment]
Hey Lauren, thanks for the reply. In the end since this was just for toying around with my own pet project I have decided to keep it local and push forward with finalizing the tool I am developing as opposed to getting it onto AWS right now. Thanks again for all of your help!

**Comment by rodrigoheck** [comment]
I am having the same problem. I am running everything from a notebook.

The training:
```
estimator = PyTorch(
    base_job_name="imdb",
    max_run= 60*30,
    entry_point="train_aws.py",
    source_dir="source",  # the dir contains the train script and a requirements.txt file
    framework_version="1.4", # PyTorch version
    py_version = 'py3',
    instance_count=1,
    role=role,  # IAM role to assume for execution
    hyperparameters=hyperparameters,
    instance_type= "ml.p3.2xlarge", 
    output_path="s3:/<bucket>/opt/ml/model", # the S3 path where model is outputted 
)

estimator.fit(
    {'training': dir}, 
    wait=True
)
```

And the deployment:

```
model = estimator.create_model(role=role)
mdm = multidatamodel.MultiDataModel(name="Models",
                                    model_data_prefix="s3://<bucket>/opt/ml/model/", 
                                    model = model,
                                    sagemaker_session=sess
                                   )
predictor = mdm.deploy(initial_instance_count=1,instance_type='ml.t2.medium', endpoint_name="inference")
```

My model_fn() function is inside train_aws.py. When I try to run the prediction, it returns the same message as Zachary's: "Please provide a model_fn implementation". I tried creating the folder "code" inside "opt/ml/model" and put the script there but had no success. Then I realized that for multimodels, the folder required was actually 'opt/ml/models/code', but that didn't work either...
